// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AanTvTipClientProgram;
impl sails_rs::client::Program for AanTvTipClientProgram {}
pub trait AanTvTipClient {
    type Env: sails_rs::client::GearEnv;
    fn aan_tv_tip(&self) -> sails_rs::client::Service<aan_tv_tip::AanTvTipImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvTipClient
    for sails_rs::client::Actor<AanTvTipClientProgram, E>
{
    type Env = E;
    fn aan_tv_tip(&self) -> sails_rs::client::Service<aan_tv_tip::AanTvTipImpl, Self::Env> {
        self.service(stringify!(AanTvTip))
    }
}
pub trait AanTvTipClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Initialise. msg::source() becomes admin.
    fn create(self) -> sails_rs::client::PendingCtor<AanTvTipClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvTipClientCtors
    for sails_rs::client::Deployment<AanTvTipClientProgram, E>
{
    type Env = E;
    fn create(self) -> sails_rs::client::PendingCtor<AanTvTipClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod aan_tv_tip {
    use super::*;
    pub trait AanTvTip {
        type Env: sails_rs::client::GearEnv;
        /// Admin-only: sweep accumulated protocol fees to admin wallet.
        fn sweep(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Sweep, Self::Env>;
        /// Send a tip to `recipient`. Takes msg::value. Splits 99% to recipient, 1% protocol.
        ///
        /// Refund correctness (sails-rs 0.10.x):
        /// - Anti-self-tip: sender == recipient → Err with full refund.
        /// - Zero value: value == 0 → Err with full refund.
        /// - Note too long: >200 bytes → Err with full refund.
        /// - Outbound send queued BEFORE state mutation.
        /// - CommandReply::with_value is the only reliable refund primitive on Err paths.
        fn tip(
            &mut self,
            recipient: ActorId,
            note: String,
        ) -> sails_rs::client::PendingCall<io::Tip, Self::Env>;
        /// Read protocol balance (for admin/tests).
        fn get_protocol_balance(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetProtocolBalance, Self::Env>;
        /// Get a tip by ID.
        fn get_tip(&self, id: u64) -> sails_rs::client::PendingCall<io::GetTip, Self::Env>;
        /// Paginated tips received by recipient. cursor=None starts from ID 1.
        fn get_tips_received(
            &self,
            recipient: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTipsReceived, Self::Env>;
        /// Paginated tips sent by sender. cursor=None starts from ID 1.
        fn get_tips_sent(
            &self,
            sender: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTipsSent, Self::Env>;
    }
    pub struct AanTvTipImpl;
    impl<E: sails_rs::client::GearEnv> AanTvTip for sails_rs::client::Service<AanTvTipImpl, E> {
        type Env = E;
        fn sweep(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Sweep, Self::Env> {
            self.pending_call((amount,))
        }
        fn tip(
            &mut self,
            recipient: ActorId,
            note: String,
        ) -> sails_rs::client::PendingCall<io::Tip, Self::Env> {
            self.pending_call((recipient, note))
        }
        fn get_protocol_balance(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetProtocolBalance, Self::Env> {
            self.pending_call(())
        }
        fn get_tip(&self, id: u64) -> sails_rs::client::PendingCall<io::GetTip, Self::Env> {
            self.pending_call((id,))
        }
        fn get_tips_received(
            &self,
            recipient: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTipsReceived, Self::Env> {
            self.pending_call((recipient, cursor, limit))
        }
        fn get_tips_sent(
            &self,
            sender: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTipsSent, Self::Env> {
            self.pending_call((sender, cursor, limit))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Sweep (amount: u128) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Tip (recipient: ActorId, note: String) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(GetProtocolBalance () -> u128);
        sails_rs::io_struct_impl!(GetTip (id: u64) -> Option<super::Tip>);
        sails_rs::io_struct_impl!(GetTipsReceived (recipient: ActorId, cursor: Option<u64>, limit: u32) -> super::TipPage);
        sails_rs::io_struct_impl!(GetTipsSent (sender: ActorId, cursor: Option<u64>, limit: u32) -> super::TipPage);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    Unauthorized,
    InsufficientPayment,
    InvalidArg,
    ArithmeticOverflow,
    InsufficientFunds,
    RefundFailed,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Tip {
    pub id: u64,
    pub sender: ActorId,
    pub recipient: ActorId,
    pub amount: u128,
    pub recipient_received: u128,
    pub protocol_cut: u128,
    pub note: String,
    pub block: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct TipPage {
    pub items: Vec<Tip>,
    pub next_cursor: Option<u64>,
}
