// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AanTvClientProgram;
impl sails_rs::client::Program for AanTvClientProgram {}
pub trait AanTvClient {
    type Env: sails_rs::client::GearEnv;
    fn aan_tv(&self) -> sails_rs::client::Service<aan_tv::AanTvImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvClient for sails_rs::client::Actor<AanTvClientProgram, E> {
    type Env = E;
    fn aan_tv(&self) -> sails_rs::client::Service<aan_tv::AanTvImpl, Self::Env> {
        self.service(stringify!(AanTv))
    }
}
pub trait AanTvClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Initialise the program. `msg::source()` becomes admin.
    fn create(self) -> sails_rs::client::PendingCtor<AanTvClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvClientCtors
    for sails_rs::client::Deployment<AanTvClientProgram, E>
{
    type Env = E;
    fn create(self) -> sails_rs::client::PendingCtor<AanTvClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod aan_tv {
    use super::*;
    pub trait AanTv {
        type Env: sails_rs::client::GearEnv;
        /// Accept an open 1v1 dice match as player_b. Caller must attach at least `buy_in` VARA.
        ///
        /// Refund correctness (sails-rs 0.10.x):
        /// - Overpayment: excess returned via `CommandReply::with_value(excess)`.
        /// - Underpayment / any Err: full `value` returned via
        /// `CommandReply::with_value(value)`.
        /// DO NOT use `msg::send` for refunds — on Err paths, outbound sends do
        /// NOT fire. `CommandReply::with_value` is the only reliable refund primitive.
        fn accept_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::AcceptMatch, Self::Env>;
        /// Commit a SHA-256 commitment for the caller's move. Free — no msg::value required.
        ///
        /// Can only be called while the match is in `InCommit` state and before
        /// `commit_deadline_block`. Both players must commit before the phase
        /// auto-advances to `InReveal`.
        fn commit(
            &mut self,
            match_id: u64,
            commitment: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::Commit, Self::Env>;
        /// Mark a coverage entry as covered by recording the bot's chat message ID.
        ///
        /// Admin only. Append-only: never removes entries (invariant #7).
        fn mark_covered(
            &mut self,
            coverage_id: u64,
            chat_msg_id: u64,
        ) -> sails_rs::client::PendingCall<io::MarkCovered, Self::Env>;
        /// Open a new 1v1 dice match. Caller must attach at least `buy_in` VARA.
        ///
        /// Refund correctness (sails-rs 0.10.x):
        /// - Overpayment: excess returned via `CommandReply::with_value(excess)`.
        /// - Underpayment / any Err: full `value` returned via
        /// `CommandReply::with_value(value)`.
        /// DO NOT use `msg::send` for refunds — on Err paths in sails-rs 0.10,
        /// outbound sends are NOT executed. `CommandReply::with_value` is the
        /// only reliable refund primitive.
        fn open_match(&mut self) -> sails_rs::client::PendingCall<io::OpenMatch, Self::Env>;
        /// Request coverage for an on-chain event. Caller must attach at least `coverage_fee` VARA.
        ///
        /// Refund correctness (sails-rs 0.10.x):
        /// - Overpayment: excess returned via `CommandReply::with_value(excess)`.
        /// - Any Err: full `value` returned via `CommandReply::with_value(value)`.
        /// DO NOT use `msg::send` for refunds.
        fn request_coverage(
            &mut self,
            event_kind: CoverageKind,
            target_program: Option<ActorId>,
            hint: String,
        ) -> sails_rs::client::PendingCall<io::RequestCoverage, Self::Env>;
        /// Resolve a match after both players have revealed (or after the reveal deadline if only
        /// one player revealed). Pays the winner 90% of the pot; the remaining 10% stays in
        /// the program as protocol cut (retrievable by admin via `sweep`).
        ///
        /// Anyone may call Resolve — the caller pays only gas and receives nothing.
        ///
        /// Decision matrix:
        /// 1. Both revealed            → winner = higher mod-100 (ties go to player_a).
        /// 2. One revealed + deadline passed → revealer wins by default.
        /// 3. Neither revealed + deadline NOT passed → Err(DeadlineNotReached).
        /// 4. Neither revealed + deadline passed → Err(DeadlineNotReached).
        /// FUTURE WORK: refund both players in case 4 (match abandoned).
        /// Currently we treat it identically to case 3; a future migration can add
        /// an `Err(MatchAbandoned)` variant and bilateral refund path.
        fn resolve(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::Resolve, Self::Env>;
        /// Reveal the preimage (`move_value`, `salt`) behind a prior commitment. Free — no msg::value.
        ///
        /// The contract verifies `SHA-256(move_value || salt) == stored_commitment`.
        /// On mismatch the caller receives `Err(RevealMismatch)` and may retry before
        /// the `reveal_deadline_block`. Resolve is handled separately (Task 11).
        fn reveal(
            &mut self,
            match_id: u64,
            move_value: u8,
            salt: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::Reveal, Self::Env>;
        /// Pull accumulated protocol fees to admin wallet.
        ///
        /// Only admin may call this. `amount` must not exceed the program's current
        /// balance minus the existential deposit or the underlying send will fail
        /// and propagate as `Err(RefundFailed)` — no special guard needed here.
        fn sweep(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Sweep, Self::Env>;
        /// Read paginated coverage queue. Returns up to `limit` entries starting from `cursor`.
        ///
        /// Cursor semantics: `None` starts from ID 1; `Some(n)` starts from ID n.
        /// Bot uses `next_cursor` as the cursor for the next poll (incremental fetch).
        fn get_coverage_queue(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetCoverageQueue, Self::Env>;
        /// Read accessor: returns the `Match` for `match_id`, or `None` if absent.
        ///
        /// Used by off-chain clients and gtests to inspect match state without
        /// exposing the full program state. This is a partial Task 14 grab — it is
        /// load-bearing for Tasks 10 and 11 tests.
        fn get_match(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetMatch, Self::Env>;
    }
    pub struct AanTvImpl;
    impl<E: sails_rs::client::GearEnv> AanTv for sails_rs::client::Service<AanTvImpl, E> {
        type Env = E;
        fn accept_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::AcceptMatch, Self::Env> {
            self.pending_call((match_id,))
        }
        fn commit(
            &mut self,
            match_id: u64,
            commitment: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::Commit, Self::Env> {
            self.pending_call((match_id, commitment))
        }
        fn mark_covered(
            &mut self,
            coverage_id: u64,
            chat_msg_id: u64,
        ) -> sails_rs::client::PendingCall<io::MarkCovered, Self::Env> {
            self.pending_call((coverage_id, chat_msg_id))
        }
        fn open_match(&mut self) -> sails_rs::client::PendingCall<io::OpenMatch, Self::Env> {
            self.pending_call(())
        }
        fn request_coverage(
            &mut self,
            event_kind: CoverageKind,
            target_program: Option<ActorId>,
            hint: String,
        ) -> sails_rs::client::PendingCall<io::RequestCoverage, Self::Env> {
            self.pending_call((event_kind, target_program, hint))
        }
        fn resolve(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::Resolve, Self::Env> {
            self.pending_call((match_id,))
        }
        fn reveal(
            &mut self,
            match_id: u64,
            move_value: u8,
            salt: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::Reveal, Self::Env> {
            self.pending_call((match_id, move_value, salt))
        }
        fn sweep(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Sweep, Self::Env> {
            self.pending_call((amount,))
        }
        fn get_coverage_queue(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetCoverageQueue, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_match(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetMatch, Self::Env> {
            self.pending_call((match_id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AcceptMatch (match_id: u64) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Commit (match_id: u64, commitment: [u8; 32]) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(MarkCovered (coverage_id: u64, chat_msg_id: u64) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(OpenMatch () -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(RequestCoverage (event_kind: super::CoverageKind, target_program: Option<ActorId>, hint: String) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(Resolve (match_id: u64) -> Result<ActorId, super::Error>);
        sails_rs::io_struct_impl!(Reveal (match_id: u64, move_value: u8, salt: [u8; 32]) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Sweep (amount: u128) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(GetCoverageQueue (cursor: Option<u64>, limit: u32) -> super::CoverageQueuePage);
        sails_rs::io_struct_impl!(GetMatch (match_id: u64) -> Option<super::Match>);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    Unauthorized,
    InsufficientPayment,
    MatchNotFound,
    WrongPhase,
    DuplicateCommit,
    RevealMismatch,
    DeadlinePassed,
    DeadlineNotReached,
    CoverageNotFound,
    AlreadyCovered,
    SelfCover,
    InvalidArg,
    ArithmeticOverflow,
    RefundFailed,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum CoverageKind {
    MarketResolved,
    BountyCompleted,
    LaunchedApp,
    MatchSettled,
    Custom,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct CoverageQueuePage {
    pub items: Vec<CoverageRequest>,
    pub next_cursor: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct CoverageRequest {
    pub id: u64,
    pub requester: ActorId,
    pub event_kind: CoverageKind,
    pub target_program: Option<ActorId>,
    pub hint: String,
    pub paid: u128,
    pub posted_at_block: u32,
    pub chat_msg_id: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Match {
    pub id: u64,
    pub player_a: ActorId,
    pub player_b: Option<ActorId>,
    pub commit_a: Option<[u8; 32]>,
    pub commit_b: Option<[u8; 32]>,
    pub reveal_a: Option<u8>,
    pub reveal_b: Option<u8>,
    pub winner: Option<ActorId>,
    pub pot: u128,
    pub commit_deadline_block: u32,
    pub reveal_deadline_block: u32,
    pub state: MatchState,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum MatchState {
    Open,
    InCommit,
    InReveal,
    Resolved,
}
