// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AanTvClientProgram;
impl sails_rs::client::Program for AanTvClientProgram {}
pub trait AanTvClient {
    type Env: sails_rs::client::GearEnv;
    fn aan_tv(&self) -> sails_rs::client::Service<aan_tv::AanTvImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvClient for sails_rs::client::Actor<AanTvClientProgram, E> {
    type Env = E;
    fn aan_tv(&self) -> sails_rs::client::Service<aan_tv::AanTvImpl, Self::Env> {
        self.service(stringify!(AanTv))
    }
}
pub trait AanTvClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(self) -> sails_rs::client::PendingCtor<AanTvClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvClientCtors
    for sails_rs::client::Deployment<AanTvClientProgram, E>
{
    type Env = E;
    fn create(self) -> sails_rs::client::PendingCtor<AanTvClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod aan_tv {
    use super::*;
    pub trait AanTv {
        type Env: sails_rs::client::GearEnv;
        fn do_something(&mut self) -> sails_rs::client::PendingCall<io::DoSomething, Self::Env>;
    }
    pub struct AanTvImpl;
    impl<E: sails_rs::client::GearEnv> AanTv for sails_rs::client::Service<AanTvImpl, E> {
        type Env = E;
        fn do_something(&mut self) -> sails_rs::client::PendingCall<io::DoSomething, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(DoSomething () -> String);
    }
}
