// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AanTvDataClientProgram;
impl sails_rs::client::Program for AanTvDataClientProgram {}
pub trait AanTvDataClient {
    type Env: sails_rs::client::GearEnv;
    fn aan_tv_data(&self) -> sails_rs::client::Service<aan_tv_data::AanTvDataImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvDataClient
    for sails_rs::client::Actor<AanTvDataClientProgram, E>
{
    type Env = E;
    fn aan_tv_data(&self) -> sails_rs::client::Service<aan_tv_data::AanTvDataImpl, Self::Env> {
        self.service(stringify!(AanTvData))
    }
}
pub trait AanTvDataClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(self)
    -> sails_rs::client::PendingCtor<AanTvDataClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvDataClientCtors
    for sails_rs::client::Deployment<AanTvDataClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AanTvDataClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod aan_tv_data {
    use super::*;
    pub trait AanTvData {
        type Env: sails_rs::client::GearEnv;
        /// Admin-only: bulk-import stats (trusted bot source). Returns count inserted.
        fn submit_batch(
            &mut self,
            stats: Vec<StatBatchEntry>,
        ) -> sails_rs::client::PendingCall<io::SubmitBatch, Self::Env>;
        /// Submit a stat entry. Requires 0.01 VARA fee (excess is refunded).
        fn submit_stat(
            &mut self,
            app: ActorId,
            kind: StatKind,
            value: u64,
            note: String,
        ) -> sails_rs::client::PendingCall<io::SubmitStat, Self::Env>;
        /// Admin-only: sweep protocol fees.
        fn sweep(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Sweep, Self::Env>;
        /// Get aggregated stats for an app.
        fn get_app_stats(
            &self,
            app: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAppStats, Self::Env>;
        /// Read protocol balance (for tests).
        fn get_protocol_balance(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetProtocolBalance, Self::Env>;
        /// Paginated recent stats. cursor=None starts from ID 1.
        fn get_recent(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetRecent, Self::Env>;
        /// Top submitters by count.
        fn get_top_callers(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTopCallers, Self::Env>;
    }
    pub struct AanTvDataImpl;
    impl<E: sails_rs::client::GearEnv> AanTvData for sails_rs::client::Service<AanTvDataImpl, E> {
        type Env = E;
        fn submit_batch(
            &mut self,
            stats: Vec<StatBatchEntry>,
        ) -> sails_rs::client::PendingCall<io::SubmitBatch, Self::Env> {
            self.pending_call((stats,))
        }
        fn submit_stat(
            &mut self,
            app: ActorId,
            kind: StatKind,
            value: u64,
            note: String,
        ) -> sails_rs::client::PendingCall<io::SubmitStat, Self::Env> {
            self.pending_call((app, kind, value, note))
        }
        fn sweep(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Sweep, Self::Env> {
            self.pending_call((amount,))
        }
        fn get_app_stats(
            &self,
            app: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAppStats, Self::Env> {
            self.pending_call((app,))
        }
        fn get_protocol_balance(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetProtocolBalance, Self::Env> {
            self.pending_call(())
        }
        fn get_recent(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetRecent, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_top_callers(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTopCallers, Self::Env> {
            self.pending_call((limit,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(SubmitBatch (stats: Vec<super::StatBatchEntry>) -> Result<u32, super::Error>);
        sails_rs::io_struct_impl!(SubmitStat (app: ActorId, kind: super::StatKind, value: u64, note: String) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(Sweep (amount: u128) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(GetAppStats (app: ActorId) -> super::AppStatsAggregate);
        sails_rs::io_struct_impl!(GetProtocolBalance () -> u128);
        sails_rs::io_struct_impl!(GetRecent (cursor: Option<u64>, limit: u32) -> super::StatPage);
        sails_rs::io_struct_impl!(GetTopCallers (limit: u32) -> Vec<super::CallerSummary>);
    }
}
/// Batch input entry (no id/block — assigned by contract).
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct StatBatchEntry {
    pub app: ActorId,
    pub kind: StatKind,
    pub value: u64,
    pub note: String,
}
/// The kind of stat being recorded.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum StatKind {
    Calls,
    Mentions,
    Posts,
    Activity,
    Custom,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    Unauthorized,
    InsufficientPayment,
    InvalidArg,
    ArithmeticOverflow,
    InsufficientFunds,
    RefundFailed,
    BatchTooLarge,
}
/// Aggregated stats for an app.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AppStatsAggregate {
    pub total_calls: u64,
    pub total_mentions: u64,
    pub total_posts: u64,
    pub latest_block: u32,
}
/// Paginated stat page.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct StatPage {
    pub items: Vec<StatEntry>,
    pub next_cursor: Option<u64>,
}
/// A single stat entry.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct StatEntry {
    pub id: u64,
    pub submitter: ActorId,
    pub app: ActorId,
    pub kind: StatKind,
    pub value: u64,
    pub note: String,
    pub block: u32,
}
/// Caller summary for GetTopCallers.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct CallerSummary {
    pub submitter: ActorId,
    pub count: u64,
}
