// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AanTvBoardClientProgram;
impl sails_rs::client::Program for AanTvBoardClientProgram {}
pub trait AanTvBoardClient {
    type Env: sails_rs::client::GearEnv;
    fn aan_tv_board(&self) -> sails_rs::client::Service<aan_tv_board::AanTvBoardImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvBoardClient
    for sails_rs::client::Actor<AanTvBoardClientProgram, E>
{
    type Env = E;
    fn aan_tv_board(&self) -> sails_rs::client::Service<aan_tv_board::AanTvBoardImpl, Self::Env> {
        self.service(stringify!(AanTvBoard))
    }
}
pub trait AanTvBoardClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Initialise the program. msg::source() becomes admin.
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AanTvBoardClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvBoardClientCtors
    for sails_rs::client::Deployment<AanTvBoardClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AanTvBoardClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod aan_tv_board {
    use super::*;
    pub trait AanTvBoard {
        type Env: sails_rs::client::GearEnv;
        /// Sign the guestbook with a thought (<=100 UTF-8 bytes). Gas-only — no msg::value taken.
        fn sign(&mut self, thought: String) -> sails_rs::client::PendingCall<io::Sign, Self::Env>;
        /// Filter entries by author ActorId.
        fn get_by_author(
            &self,
            author: ActorId,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetByAuthor, Self::Env>;
        /// Paginated entry list. cursor=None starts from ID 1.
        fn get_entries(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetEntries, Self::Env>;
        /// Read full state (for tests and admin introspection).
        fn read_state(&self) -> sails_rs::client::PendingCall<io::ReadState, Self::Env>;
    }
    pub struct AanTvBoardImpl;
    impl<E: sails_rs::client::GearEnv> AanTvBoard for sails_rs::client::Service<AanTvBoardImpl, E> {
        type Env = E;
        fn sign(&mut self, thought: String) -> sails_rs::client::PendingCall<io::Sign, Self::Env> {
            self.pending_call((thought,))
        }
        fn get_by_author(
            &self,
            author: ActorId,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetByAuthor, Self::Env> {
            self.pending_call((author, limit))
        }
        fn get_entries(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetEntries, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn read_state(&self) -> sails_rs::client::PendingCall<io::ReadState, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Sign (thought: String) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(GetByAuthor (author: ActorId, limit: u32) -> Vec<super::Entry>);
        sails_rs::io_struct_impl!(GetEntries (cursor: Option<u64>, limit: u32) -> super::EntryPage);
        sails_rs::io_struct_impl!(ReadState () -> Vec<super::Entry>);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    Unauthorized,
    InvalidArg,
    ArithmeticOverflow,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Entry {
    pub id: u64,
    pub author: ActorId,
    pub author_kind: String,
    pub thought: String,
    pub block: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct EntryPage {
    pub items: Vec<Entry>,
    pub next_cursor: Option<u64>,
}
