// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AanTvRelayClientProgram;
impl sails_rs::client::Program for AanTvRelayClientProgram {}
pub trait AanTvRelayClient {
    type Env: sails_rs::client::GearEnv;
    fn aan_tv_relay(&self) -> sails_rs::client::Service<aan_tv_relay::AanTvRelayImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvRelayClient
    for sails_rs::client::Actor<AanTvRelayClientProgram, E>
{
    type Env = E;
    fn aan_tv_relay(&self) -> sails_rs::client::Service<aan_tv_relay::AanTvRelayImpl, Self::Env> {
        self.service(stringify!(AanTvRelay))
    }
}
pub trait AanTvRelayClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Initialise the program. msg::source() becomes admin.
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AanTvRelayClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanTvRelayClientCtors
    for sails_rs::client::Deployment<AanTvRelayClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AanTvRelayClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod aan_tv_relay {
    use super::*;
    pub trait AanTvRelay {
        type Env: sails_rs::client::GearEnv;
        /// Admin: append a program ActorId to the outbound ping list.
        /// Idempotent: duplicate targets are a no-op.
        fn add_ping_target(
            &mut self,
            target: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddPingTarget, Self::Env>;
        /// Admin: remove a target from the outbound ping list.
        fn remove_ping_target(
            &mut self,
            target: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemovePingTarget, Self::Env>;
        /// Permissionless: fan out a zero-value heartbeat to every target.
        /// Throttled to one successful call per `TICK_MIN_BLOCK_GAP` blocks.
        /// Each outbound is sent FROM this program actor, so the indexer
        /// attributes the call as `origin: program_initiated` to the relay's
        /// appMetric. Returns the number of targets pinged on success.
        fn tick(&mut self) -> sails_rs::client::PendingCall<io::Tick, Self::Env>;
        /// Query: read the admin ActorId.
        fn get_admin(&self) -> sails_rs::client::PendingCall<io::GetAdmin, Self::Env>;
        /// Query: read the block of the last successful Tick.
        fn get_last_tick_block(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetLastTickBlock, Self::Env>;
        /// Query: read the current ping target list.
        fn get_ping_targets(&self) -> sails_rs::client::PendingCall<io::GetPingTargets, Self::Env>;
        /// Query: read the lifetime ping count emitted by this relay.
        fn get_total_pings_sent(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetTotalPingsSent, Self::Env>;
    }
    pub struct AanTvRelayImpl;
    impl<E: sails_rs::client::GearEnv> AanTvRelay for sails_rs::client::Service<AanTvRelayImpl, E> {
        type Env = E;
        fn add_ping_target(
            &mut self,
            target: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddPingTarget, Self::Env> {
            self.pending_call((target,))
        }
        fn remove_ping_target(
            &mut self,
            target: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemovePingTarget, Self::Env> {
            self.pending_call((target,))
        }
        fn tick(&mut self) -> sails_rs::client::PendingCall<io::Tick, Self::Env> {
            self.pending_call(())
        }
        fn get_admin(&self) -> sails_rs::client::PendingCall<io::GetAdmin, Self::Env> {
            self.pending_call(())
        }
        fn get_last_tick_block(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetLastTickBlock, Self::Env> {
            self.pending_call(())
        }
        fn get_ping_targets(&self) -> sails_rs::client::PendingCall<io::GetPingTargets, Self::Env> {
            self.pending_call(())
        }
        fn get_total_pings_sent(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetTotalPingsSent, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddPingTarget (target: ActorId) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(RemovePingTarget (target: ActorId) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(Tick () -> Result<u32, super::Error>);
        sails_rs::io_struct_impl!(GetAdmin () -> ActorId);
        sails_rs::io_struct_impl!(GetLastTickBlock () -> u32);
        sails_rs::io_struct_impl!(GetPingTargets () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(GetTotalPingsSent () -> u64);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    Unauthorized,
    TooManyPingTargets,
    PingTargetNotFound,
    TickThrottled,
}
