// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AanMissionsClientProgram;
impl sails_rs::client::Program for AanMissionsClientProgram {}
pub trait AanMissionsClient {
    type Env: sails_rs::client::GearEnv;
    fn aan_missions(&self) -> sails_rs::client::Service<aan_missions::AanMissionsImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanMissionsClient
    for sails_rs::client::Actor<AanMissionsClientProgram, E>
{
    type Env = E;
    fn aan_missions(&self) -> sails_rs::client::Service<aan_missions::AanMissionsImpl, Self::Env> {
        self.service(stringify!(AanMissions))
    }
}
pub trait AanMissionsClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AanMissionsClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AanMissionsClientCtors
    for sails_rs::client::Deployment<AanMissionsClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AanMissionsClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod aan_missions {
    use super::*;
    pub trait AanMissions {
        type Env: sails_rs::client::GearEnv;
        fn approve_proof(
            &mut self,
            proof_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApproveProof, Self::Env>;
        fn claim_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimMission, Self::Env>;
        fn close_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::CloseMission, Self::Env>;
        fn create_mission(
            &mut self,
            input: MissionInput,
        ) -> sails_rs::client::PendingCall<io::CreateMission, Self::Env>;
        fn reject_proof(
            &mut self,
            proof_id: u64,
            reason: String,
        ) -> sails_rs::client::PendingCall<io::RejectProof, Self::Env>;
        fn submit_proof(
            &mut self,
            mission_id: u64,
            proof_tx_hash: String,
            note: String,
        ) -> sails_rs::client::PendingCall<io::SubmitProof, Self::Env>;
        fn get_agent_record(
            &self,
            agent: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgentRecord, Self::Env>;
        fn get_agent_records(
            &self,
            cursor: Option<u32>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetAgentRecords, Self::Env>;
        fn get_claims(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetClaims, Self::Env>;
        fn get_claims_by_agent(
            &self,
            agent: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetClaimsByAgent, Self::Env>;
        fn get_mission(
            &self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetMission, Self::Env>;
        fn get_missions(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMissions, Self::Env>;
        fn get_open_missions(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetOpenMissions, Self::Env>;
        fn get_pending_proofs(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPendingProofs, Self::Env>;
        fn get_proof(
            &self,
            proof_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetProof, Self::Env>;
        fn get_proofs(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetProofs, Self::Env>;
        fn get_stats(&self) -> sails_rs::client::PendingCall<io::GetStats, Self::Env>;
    }
    pub struct AanMissionsImpl;
    impl<E: sails_rs::client::GearEnv> AanMissions for sails_rs::client::Service<AanMissionsImpl, E> {
        type Env = E;
        fn approve_proof(
            &mut self,
            proof_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApproveProof, Self::Env> {
            self.pending_call((proof_id,))
        }
        fn claim_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimMission, Self::Env> {
            self.pending_call((mission_id,))
        }
        fn close_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::CloseMission, Self::Env> {
            self.pending_call((mission_id,))
        }
        fn create_mission(
            &mut self,
            input: MissionInput,
        ) -> sails_rs::client::PendingCall<io::CreateMission, Self::Env> {
            self.pending_call((input,))
        }
        fn reject_proof(
            &mut self,
            proof_id: u64,
            reason: String,
        ) -> sails_rs::client::PendingCall<io::RejectProof, Self::Env> {
            self.pending_call((proof_id, reason))
        }
        fn submit_proof(
            &mut self,
            mission_id: u64,
            proof_tx_hash: String,
            note: String,
        ) -> sails_rs::client::PendingCall<io::SubmitProof, Self::Env> {
            self.pending_call((mission_id, proof_tx_hash, note))
        }
        fn get_agent_record(
            &self,
            agent: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgentRecord, Self::Env> {
            self.pending_call((agent,))
        }
        fn get_agent_records(
            &self,
            cursor: Option<u32>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetAgentRecords, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_claims(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetClaims, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_claims_by_agent(
            &self,
            agent: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetClaimsByAgent, Self::Env> {
            self.pending_call((agent, cursor, limit))
        }
        fn get_mission(
            &self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetMission, Self::Env> {
            self.pending_call((mission_id,))
        }
        fn get_missions(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMissions, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_open_missions(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetOpenMissions, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_pending_proofs(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPendingProofs, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_proof(
            &self,
            proof_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetProof, Self::Env> {
            self.pending_call((proof_id,))
        }
        fn get_proofs(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetProofs, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_stats(&self) -> sails_rs::client::PendingCall<io::GetStats, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ApproveProof (proof_id: u64) -> Result<super::RewardPaid, super::Error>);
        sails_rs::io_struct_impl!(ClaimMission (mission_id: u64) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(CloseMission (mission_id: u64) -> Result<super::RefundAmount, super::Error>);
        sails_rs::io_struct_impl!(CreateMission (input: super::MissionInput) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(RejectProof (proof_id: u64, reason: String) -> Result<(), super::Error>);
        sails_rs::io_struct_impl!(SubmitProof (mission_id: u64, proof_tx_hash: String, note: String) -> Result<u64, super::Error>);
        sails_rs::io_struct_impl!(GetAgentRecord (agent: ActorId) -> super::AgentRecord);
        sails_rs::io_struct_impl!(GetAgentRecords (cursor: Option<u32>, limit: u32) -> super::AgentRecordPage);
        sails_rs::io_struct_impl!(GetClaims (cursor: Option<u64>, limit: u32) -> super::ClaimPage);
        sails_rs::io_struct_impl!(GetClaimsByAgent (agent: ActorId, cursor: Option<u64>, limit: u32) -> super::ClaimPage);
        sails_rs::io_struct_impl!(GetMission (mission_id: u64) -> Option<super::Mission>);
        sails_rs::io_struct_impl!(GetMissions (cursor: Option<u64>, limit: u32) -> super::MissionPage);
        sails_rs::io_struct_impl!(GetOpenMissions (cursor: Option<u64>, limit: u32) -> super::MissionPage);
        sails_rs::io_struct_impl!(GetPendingProofs (cursor: Option<u64>, limit: u32) -> super::ProofPage);
        sails_rs::io_struct_impl!(GetProof (proof_id: u64) -> Option<super::Proof>);
        sails_rs::io_struct_impl!(GetProofs (cursor: Option<u64>, limit: u32) -> super::ProofPage);
        sails_rs::io_struct_impl!(GetStats () -> super::MissionStats);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RewardPaid {
    pub proof_id: u64,
    pub mission_id: u64,
    pub claimant: ActorId,
    pub amount: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    Unauthorized,
    InvalidArg,
    InsufficientPayment,
    MissionNotFound,
    MissionClosed,
    MissionExpired,
    MissionFull,
    ClaimNotFound,
    DuplicateClaim,
    DuplicateProof,
    ProofNotFound,
    WrongStatus,
    RewardPoolEmpty,
    ArithmeticOverflow,
    PayoutFailed,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RefundAmount {
    pub mission_id: u64,
    pub amount: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MissionInput {
    pub title: String,
    pub instructions: String,
    pub target_program: Option<ActorId>,
    pub required_action: String,
    pub reward: u128,
    pub max_approvals: u32,
    pub deadline_block: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AgentRecord {
    pub agent: ActorId,
    pub completed_count: u32,
    pub total_rewards_earned: u128,
    pub rejected_proof_count: u32,
    pub last_completed_block: u32,
    pub distinct_targets: Vec<ActorId>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AgentRecordPage {
    pub items: Vec<AgentRecord>,
    pub next_cursor: Option<u32>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ClaimPage {
    pub items: Vec<Claim>,
    pub next_cursor: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Claim {
    pub id: u64,
    pub mission_id: u64,
    pub claimant: ActorId,
    pub claimed_at_block: u32,
    pub status: ClaimStatus,
    pub latest_proof_id: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ClaimStatus {
    Claimed,
    ProofPending,
    Approved,
    Rejected,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Mission {
    pub id: u64,
    pub title: String,
    pub instructions: String,
    pub target_program: Option<ActorId>,
    pub required_action: String,
    pub reward: u128,
    pub max_approvals: u32,
    pub approvals_count: u32,
    pub deadline_block: u32,
    pub created_at_block: u32,
    pub closed: bool,
    pub funded_pool: u128,
    pub remaining_pool: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MissionPage {
    pub items: Vec<Mission>,
    pub next_cursor: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ProofPage {
    pub items: Vec<Proof>,
    pub next_cursor: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Proof {
    pub id: u64,
    pub mission_id: u64,
    pub claim_id: u64,
    pub claimant: ActorId,
    pub proof_tx_hash: String,
    pub note: String,
    pub submitted_at_block: u32,
    pub status: ProofStatus,
    pub rejection_reason: Option<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ProofStatus {
    Pending,
    Approved,
    Rejected,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MissionStats {
    pub total_missions: u64,
    pub open_missions: u64,
    pub total_claims: u64,
    pub pending_proofs: u64,
    pub approved_proofs: u64,
    pub rejected_proofs: u64,
    pub rewards_paid: u128,
    pub rewards_remaining: u128,
}
